//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Debatron_v9
{
    using System;
    using System.Collections.Generic;
    
    public partial class thread
    {
        public int Thread_ID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int CreatorUser_ID { get; set; }
        public string ThreadTitle { get; set; }
    
        public virtual user user { get; set; }
    }
}
